version: '3.9'

services:

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - my_network

  backend:
    build:
      context: ./backend
    ports:
      - "1234:1234"
    depends_on:
      - db
      - localstack
    networks:
      - my_network

  localstack:
    build:
      context: ./s3
    environment:
      - SERVICES=s3
    ports:
      - "127.0.0.1:4566:4566" 
    networks:
        - my_network

  db:
    build:
      context: ./database
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=filesystem_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    networks:
      - my_network

networks:
  my_network:
    driver: bridge